sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  flowdock: e7454f5285e7b9ab67009802d5560490
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: PwYASEjgtHXjS0WUYJUYyJ4f/T27oeK+ZiW7WTc1cpR7T8VDbJ8ADAEvTruok1psZTUl1f466ECdVmytLEcrYkZQyKfLLfF338Gq4PeGLuF7pXwrX+rg2/+gp8S4rWF7/hGyo1SeMwmoPyuPY4+INO7h32oUO1DP62L8LTzT+dE=
  on:
    tags: true
    all_branches: true
