language: node_js
cache:
  bundler: true
  directories:
    - node_modules
node_js:
- '0.10'
addons:
  apt:
    packages:
    - libbluetooth-dev
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: "CuRu5yXkv1iA6rp9WXcjf71AYM5ah4/YaOqSqj+o6nb9tKI9Uj68WwmpHW6REJ95Iy+k0QqxGktQ1ZQNOV8T0+sDzGtTVYqwtubewZqXKSRMsQ47eTkWO9WpA9cmVVtojBKvXKg0DmMaV1ZJ3Lxwxa36SZD4vzQaCJXy9fvKLAA="
  on:
    tags: true
    all_branches: true
